// VANI AI - Core TypeScript Types

// ============ User & Auth Types ============
export type UserRole = 'child' | 'therapist' | 'parent';

export interface User {
  id: string;
  email?: string;
  phone?: string;
  name: string;
  role: UserRole;
  avatarUrl?: string;
  createdAt: number;
  updatedAt: number;
}

// ============ Child Profile ============
export type SupportedLanguage = 
  | 'hindi' 
  | 'tamil' 
  | 'telugu' 
  | 'kannada' 
  | 'malayalam' 
  | 'marathi' 
  | 'bengali' 
  | 'english';

export interface ChildProfile {
  id: string;
  userId: string;
  name: string;
  age?: number;
  avatarId: string;
  languagePrefs: SupportedLanguage[];
  primaryLanguage: SupportedLanguage;
  streak: number;
  xp: number;
  hearts: number;
  maxHearts: number;
  level: number;
  badges: string[];
  lastActiveAt: number;
  createdAt: number;
  updatedAt: number;
  // Therapist assignment
  therapistId?: string;
  clinicId?: string;
}

// ============ Assessment Packs & Cards ============
export type CardType = 
  | 'word' 
  | 'picture' 
  | 'sentence' 
  | 'minimal_pair' 
  | 'repetition' 
  | 'spontaneous';

export type DifficultyLevel = 'easy' | 'medium' | 'hard';

export interface Card {
  id: string;
  packId: string;
  type: CardType;
  order: number;
  // Symbol/Image
  symbolId?: string;
  imageUrl?: string;
  // Prompts in multiple languages
  promptByLang: Record<SupportedLanguage, string>;
  // Expected response for scoring
  expectedByLang: Record<SupportedLanguage, string>;
  // Phoneme targets
  targetPhonemes: string[];
  // Instructions/tips for therapist or child
  tip?: string;
  // Reference audio recorded by therapist
  referenceAudioUrl?: string;
  referenceAudioBlob?: Blob;
  createdAt: number;
  updatedAt: number;
}

export interface Pack {
  id: string;
  name: string;
  description?: string;
  // Primary language and supported languages
  language: SupportedLanguage;
  supportedLanguages: SupportedLanguage[];
  // Target phonemes for this pack
  targetPhonemes: string[];
  // Difficulty
  difficulty: DifficultyLevel;
  level: number;
  // Cards
  cards: Card[];
  cardIds: string[];
  // Metadata
  category?: string;
  tags?: string[];
  thumbnailUrl?: string;
  // Authoring
  authorId: string;
  isPublished: boolean;
  // Thresholds
  passThreshold: number; // Percentage to pass (e.g., 80)
  // Stats
  totalAttempts: number;
  avgAccuracy: number;
  createdAt: number;
  updatedAt: number;
}

// ============ Attempts & Sessions ============
export type PhonemeErrorType = 
  | 'substitution' 
  | 'omission' 
  | 'distortion' 
  | 'addition' 
  | 'none';

export interface PhonemeError {
  target: string;
  actual?: string;
  errorType: PhonemeErrorType;
  position: number; // Character position in word
  severity: 'mild' | 'moderate' | 'severe';
}

export interface Attempt {
  id: string;
  timestamp: number;
  childId: string;
  packId: string;
  cardId: string;
  // Audio
  audioUrl?: string;
  audioBlob?: Blob;
  audioDuration?: number;
  // Transcript
  expected: string;
  transcript?: string;
  manualTranscript?: string;
  // Scoring
  accuracy: number; // 0-100
  isCorrect: boolean;
  // Phoneme analysis
  phonemeTarget: string;
  phonemeErrors: PhonemeError[];
  errorType: PhonemeErrorType;
  // Metadata
  language: SupportedLanguage;
  sessionId?: string;
  // Sync status
  synced: boolean;
  syncedAt?: number;
}

export interface Session {
  id: string;
  therapistId?: string;
  childId: string;
  packId: string;
  // Attempts in this session
  attemptIds: string[];
  attempts?: Attempt[];
  // Session metadata
  startedAt: number;
  endedAt?: number;
  duration?: number;
  // Results
  totalCards: number;
  completedCards: number;
  correctCards: number;
  accuracy: number;
  passed: boolean;
  xpEarned: number;
  // Teletherapy
  isTeletherapy: boolean;
  roomId?: string;
  // Documentation
  soapNote?: SOAPNote;
  therapyPlan?: TherapyPlan;
  clinicianNotes?: string;
  // Sync
  synced: boolean;
}

// ============ Clinical Documentation ============
export interface SOAPNote {
  id: string;
  sessionId: string;
  childId: string;
  therapistId: string;
  // SOAP sections
  subjective: string;
  objective: string;
  assessment: string;
  plan: string;
  // Metadata
  isAutoGenerated: boolean;
  isEdited: boolean;
  createdAt: number;
  updatedAt: number;
}

export interface TherapyExercise {
  id: string;
  name: string;
  description: string;
  targetPhonemes: string[];
  duration: number; // minutes
  frequency: 'daily' | 'weekly' | '2x_daily';
  materials?: string[];
  instructions: string[];
}

export interface TherapyPlan {
  id: string;
  childId: string;
  therapistId: string;
  // Goals
  shortTermGoals: string[];
  longTermGoals: string[];
  // Exercises
  exercises: TherapyExercise[];
  // Schedule
  dailyDuration: number; // minutes
  weeklyFrequency: number;
  startDate: number;
  endDate?: number;
  // Status
  status: 'draft' | 'active' | 'completed' | 'paused';
  // Metadata
  isAutoGenerated: boolean;
  createdAt: number;
  updatedAt: number;
}

// ============ Progress & Analytics ============
export interface ProgressSnapshot {
  id: string;
  childId: string;
  date: number; // timestamp for the day
  // Accuracy by phoneme
  accuracyByPhoneme: Record<string, number>;
  // Overall stats
  overallAccuracy: number;
  sessionsCompleted: number;
  cardsAttempted: number;
  xpEarned: number;
  streakMaintained: boolean;
}

export interface WeakTarget {
  phoneme: string;
  accuracy: number;
  attemptCount: number;
  lastAttemptAt: number;
  trend: 'improving' | 'declining' | 'stable';
}

// ============ Symbol Library ============
export interface Symbol {
  id: string;
  name: string;
  nameByLang: Record<SupportedLanguage, string>;
  category: string;
  subcategory?: string;
  imageUrl: string;
  // For offline
  imageBlob?: Blob;
  // Tags for search
  tags: string[];
  // Cultural relevance
  culturalContext?: string;
  isIndiaRelevant: boolean;
}

export type SymbolCategory = 
  | 'animals'
  | 'food'
  | 'household'
  | 'body_parts'
  | 'actions'
  | 'nature'
  | 'transport'
  | 'clothing'
  | 'family'
  | 'emotions'
  | 'numbers'
  | 'colors'
  | 'shapes'
  | 'festivals'
  | 'professions';

// ============ Teletherapy ============
export interface TeletherapyRoom {
  id: string;
  sessionId: string;
  therapistId: string;
  childId: string;
  // Room state
  status: 'waiting' | 'active' | 'ended';
  createdAt: number;
  startedAt?: number;
  endedAt?: number;
  // Current card being shown
  currentCardId?: string;
}

// ============ Sync Queue ============
export type SyncItemKind = 
  | 'attempt' 
  | 'session' 
  | 'profile' 
  | 'pack' 
  | 'progress';

export interface SyncQueueItem {
  id: string;
  kind: SyncItemKind;
  operation: 'create' | 'update' | 'delete';
  payload: unknown;
  status: 'pending' | 'syncing' | 'synced' | 'failed';
  retryCount: number;
  createdAt: number;
  lastAttemptAt?: number;
  error?: string;
}

// ============ App State ============
export interface AppSettings {
  theme: 'light' | 'dark' | 'system';
  fontSize: 'normal' | 'large' | 'extra-large';
  highContrast: boolean;
  hapticFeedback: boolean;
  soundEffects: boolean;
  lowBandwidthMode: boolean;
  offlineMode: boolean;
  autoSync: boolean;
  language: SupportedLanguage;
}

// ============ Parent Community ============
export interface CommunityPost {
  id: string;
  authorId: string;
  authorName: string;
  authorAvatar?: string;
  content: string;
  likes: number;
  comments: number;
  createdAt: number;
  isLocal: boolean; // For offline-first
}

// ============ Quest Map ============
export interface QuestNode {
  id: string;
  packId: string;
  order: number;
  status: 'locked' | 'unlocked' | 'completed' | 'current';
  stars: 0 | 1 | 2 | 3;
  bestAccuracy: number;
  attempts: number;
}

export interface QuestMap {
  childId: string;
  language: SupportedLanguage;
  currentLevel: number;
  nodes: QuestNode[];
  updatedAt: number;
}

// ============ Feature Flags ============
export interface FeatureFlags {
  cloudSync: boolean;
  asrProduction: boolean;
  llmSoap: boolean;
  llmTherapyPlan: boolean;
  teletherapy: boolean;
  parentCommunity: boolean;
}
